# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build-local:
    cmds:
      - go build -o resizer ./cmd/resizer/main.go
    silent: true
    desc: build the application

  run-local:
    cmds:
      - go run ./cmd/resizer/main.go
    silent: true
    desc: run the application

  test:
    cmds:
      - go test -race -count 100 ./...
    silent: true
    desc: run tests

  lint:
    cmds:
      - golangci-lint run
    silent: true
    desc: run linters