# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Linter
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1.6

    - name: Test
      run: go test -coverprofile=coverage-unit.out -race -count 100 ./...
      
    - name: Integration Test
      run: go test -tags=integration -coverprofile=coverage-integration.out ./tests/...

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
        files: coverage-unit.out coverage-integration.out
